version: "3.8"

services:
  sveltekit:
    build:
      context: ./frontend-svelte
    ports:
      - "3001:3000"
    environment:
      - API_URL=http://laravel # Use `laravel` as the hostname and default port 80
      - AUTH_SECRET=${AUTH_SECRET}
      - ORIGIN=${ORIGIN}
      - NODE_ENV=production
    depends_on:
      - laravel # Ensure the backend is started before the frontend

  laravel:
    build:
      context: ./backend-laravel
    ports:
      - "8181:80" # Map container's Apache port 80 to host port 8181
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
