version: "3.8"

services:
  sveltekit:
    build:
      context: ./frontend-svelte
    ports:
      - "3001:3000"
    environment:
      - API_URL=http://laravel # Use `laravel` as the hostname and default port 80
      - AUTH_SECRET=${AUTH_SECRET}
      - ORIGIN=${ORIGIN}
      - NODE_ENV=production
    depends_on:
      - laravel
    networks:
      - washed_network

  laravel:
    build:
      context: ./backend-laravel
    ports:
      - "8181:80"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    networks:
      - washed_network

  cron:
    image: alpine/curl
    command: >
      sh -c "
        echo '*/10 * * * * curl -X GET http://laravel/api/cron/test' > /etc/crontabs/root && \
        crond -f -l 2
      "
    depends_on:
      - laravel
    networks:
      - washed_network

networks:
  washed_network:
    driver: bridge
